// data.jsx — sample content for foodnme prototype

const CATEGORIES = [
  { slug: "all",       label: "All",                tag: "neutral" },
  { slug: "food-safety",       label: "Food Safety",       tag: "green" },
  { slug: "quality-control",   label: "Quality Control",   tag: "safe" },
  { slug: "regulatory",        label: "Regulatory",        tag: "orange" },
  { slug: "processing",        label: "Processing",        tag: "neutral" },
  { slug: "industry-insights", label: "Industry Insights", tag: "accent" },
];

const TEMPLATE_CATEGORIES = [
  { slug: "all",                 label: "All",                tag: "neutral" },
  { slug: "haccp",               label: "HACCP",              tag: "green" },
  { slug: "audit-checklists",    label: "Audit Checklists",   tag: "safe" },
  { slug: "sop-templates",       label: "SOP Templates",      tag: "neutral" },
  { slug: "qc-inspection",       label: "QC Inspection",      tag: "orange" },
  { slug: "compliance-docs",     label: "Compliance Docs",    tag: "accent" },
];

const ARTICLES = [
  {
    slug: "haccp-implementation-small-food-businesses",
    title: "A practical HACCP rollout for small food businesses",
    excerpt: "How to scope, document, and verify a HACCP plan without a 200-page binder. The shortest path to a defensible system.",
    category: "food-safety",
    categoryLabel: "Food Safety",
    readTime: 9,
    publishedAt: "May 12, 2026",
    author: "Aarti Menon",
    authorRole: "FSSAI Auditor · 12 yrs",
    tags: ["HACCP", "FSSAI", "Compliance"],
    cover: "https://images.unsplash.com/photo-1581094288338-2314dddb7ece?w=1200&q=80&auto=format&fit=crop",
    featured: true,
  },
  {
    slug: "fssai-licensing-changes-2026",
    title: "FSSAI licensing updates that matter in 2026",
    excerpt: "Three changes to renewal timelines, a new category for cell-cultured products, and what's changed for nutraceuticals.",
    category: "regulatory",
    categoryLabel: "Regulatory",
    readTime: 6,
    publishedAt: "May 08, 2026",
    author: "Vikram Shah",
    authorRole: "Regulatory Consultant",
    tags: ["FSSAI", "Regulatory"],
    cover: "https://images.unsplash.com/photo-1532634922-8fe0b757fb13?w=1200&q=80&auto=format&fit=crop",
  },
  {
    slug: "shelf-life-testing-protocols",
    title: "Designing a shelf-life study that holds up to audit",
    excerpt: "Accelerated vs. real-time, sample sizes, and the documentation auditors actually look for.",
    category: "quality-control",
    categoryLabel: "Quality Control",
    readTime: 11,
    publishedAt: "May 03, 2026",
    author: "Priya Iyer",
    authorRole: "QC Manager · Dairy",
    tags: ["Shelf Life", "Testing", "Microbiology"],
    cover: "https://images.unsplash.com/photo-1582719471384-894fbb16e074?w=1200&q=80&auto=format&fit=crop",
  },
  {
    slug: "allergen-cross-contact-controls",
    title: "Allergen cross-contact: the controls auditors look for",
    excerpt: "Cleaning validation, line scheduling, and labeling errors that have triggered recalls in the past 18 months.",
    category: "food-safety",
    categoryLabel: "Food Safety",
    readTime: 8,
    publishedAt: "Apr 28, 2026",
    author: "Aarti Menon",
    authorRole: "FSSAI Auditor · 12 yrs",
    tags: ["Allergens", "GMP"],
    cover: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=1200&q=80&auto=format&fit=crop",
  },
  {
    slug: "thermal-process-validation",
    title: "Thermal process validation without the math anxiety",
    excerpt: "F0 values, come-up time, and a worked example for a low-acid canned product line.",
    category: "processing",
    categoryLabel: "Processing",
    readTime: 13,
    publishedAt: "Apr 22, 2026",
    author: "Devansh Roy",
    authorRole: "Process Engineer",
    tags: ["Thermal", "Validation"],
    cover: "https://images.unsplash.com/photo-1565895405138-6c3a1555da6a?w=1200&q=80&auto=format&fit=crop",
  },
  {
    slug: "sampling-plans-q-c-2026",
    title: "Sampling plans for incoming QC: what's enough?",
    excerpt: "AQL vs. zero-acceptance, when to switch, and how to negotiate sampling levels with suppliers.",
    category: "quality-control",
    categoryLabel: "Quality Control",
    readTime: 7,
    publishedAt: "Apr 18, 2026",
    author: "Priya Iyer",
    authorRole: "QC Manager · Dairy",
    tags: ["Sampling", "Inspection"],
    cover: "https://images.unsplash.com/photo-1567427018141-0584cfcbf1b8?w=1200&q=80&auto=format&fit=crop",
  },
  {
    slug: "indian-food-tech-funding-2026",
    title: "Where Indian food-tech capital is flowing in 2026",
    excerpt: "Cell-cultured, gut health, and the unexpected rise of B2B ingredient platforms. Numbers from the first quarter.",
    category: "industry-insights",
    categoryLabel: "Industry Insights",
    readTime: 5,
    publishedAt: "Apr 14, 2026",
    author: "Naina Kapoor",
    authorRole: "Industry Analyst",
    tags: ["Funding", "Trends"],
    cover: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=1200&q=80&auto=format&fit=crop",
  },
  {
    slug: "labeling-compliance-checklist",
    title: "Labeling compliance: the 12 errors we see repeatedly",
    excerpt: "Nutrition panel formatting, allergen declarations, and front-of-pack changes you might have missed.",
    category: "regulatory",
    categoryLabel: "Regulatory",
    readTime: 10,
    publishedAt: "Apr 09, 2026",
    author: "Vikram Shah",
    authorRole: "Regulatory Consultant",
    tags: ["Labeling", "FSSAI"],
    cover: "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=1200&q=80&auto=format&fit=crop",
  },
  {
    slug: "extrusion-troubleshooting",
    title: "Troubleshooting extrusion: density, expansion, and burn marks",
    excerpt: "A field guide for snack and breakfast cereal lines. With a screw configuration cheat sheet.",
    category: "processing",
    categoryLabel: "Processing",
    readTime: 14,
    publishedAt: "Apr 02, 2026",
    author: "Devansh Roy",
    authorRole: "Process Engineer",
    tags: ["Extrusion", "Troubleshooting"],
    cover: "https://images.unsplash.com/photo-1606787366850-de6330128bfc?w=1200&q=80&auto=format&fit=crop",
  },
];

const TEMPLATES = [
  {
    slug: "haccp-plan-template-dairy",
    title: "HACCP Plan Template — Dairy Processing",
    description: "Complete HACCP plan structure with hazard analysis, CCP determination matrix, and monitoring forms tailored for dairy lines.",
    category: "haccp",
    categoryLabel: "HACCP",
    fileType: "DOCX",
    pages: 28,
    downloads: 1840,
    updatedAt: "March 2026",
    sections: [
      "Hazard identification worksheet",
      "Decision tree for CCPs",
      "Monitoring procedures (T/RH/pH)",
      "Corrective action log",
      "Verification & validation records",
      "Annual review checklist",
    ],
  },
  {
    slug: "supplier-audit-checklist",
    title: "Supplier Audit Checklist (GFSI-Aligned)",
    description: "200-point audit checklist used by procurement teams to qualify ingredient and packaging suppliers.",
    category: "audit-checklists",
    categoryLabel: "Audit Checklists",
    fileType: "PDF",
    pages: 14,
    downloads: 2310,
    updatedAt: "February 2026",
    sections: [
      "Facility & infrastructure",
      "Pest control & sanitation",
      "Allergen management",
      "Traceability & recall capability",
      "Document & record control",
    ],
  },
  {
    slug: "sop-cip-cleaning",
    title: "SOP — CIP Cleaning for Liquid Lines",
    description: "Step-by-step Cleaning-in-Place SOP with chemical concentrations, temperature ranges, and verification logs.",
    category: "sop-templates",
    categoryLabel: "SOP Templates",
    fileType: "DOCX",
    pages: 8,
    downloads: 1260,
    updatedAt: "April 2026",
    sections: [
      "Pre-rinse stage parameters",
      "Caustic wash protocols",
      "Acid sanitization steps",
      "Final rinse verification",
      "Visual & ATP swab logs",
    ],
  },
  {
    slug: "qc-inspection-incoming-materials",
    title: "QC Inspection Sheet — Incoming Materials",
    description: "Lot-level inspection record for raw materials including AQL tables and disposition workflow.",
    category: "qc-inspection",
    categoryLabel: "QC Inspection",
    fileType: "PDF",
    pages: 6,
    downloads: 980,
    updatedAt: "March 2026",
    sections: [
      "Lot identification & sampling",
      "Sensory & physical checks",
      "Lab analysis fields",
      "Disposition: accept / reject / hold",
    ],
  },
  {
    slug: "fssai-license-renewal-checklist",
    title: "FSSAI License Renewal Checklist",
    description: "Annual document review and renewal workflow with timelines, required attachments, and a fee schedule.",
    category: "compliance-docs",
    categoryLabel: "Compliance Docs",
    fileType: "PDF",
    pages: 4,
    downloads: 3120,
    updatedAt: "May 2026",
    sections: [
      "Pre-renewal document audit",
      "Required attachments",
      "Fee schedule by tier",
      "Submission timeline",
    ],
  },
  {
    slug: "haccp-team-charter",
    title: "HACCP Team Charter & Roles Template",
    description: "Defines team composition, decision authority, and the cadence of HACCP review meetings.",
    category: "haccp",
    categoryLabel: "HACCP",
    fileType: "DOCX",
    pages: 5,
    downloads: 720,
    updatedAt: "January 2026",
    sections: [
      "Team composition matrix",
      "Roles & responsibilities",
      "Meeting cadence",
      "Document approval chain",
    ],
  },
  {
    slug: "internal-audit-plan",
    title: "Annual Internal Audit Plan",
    description: "Quarterly audit calendar template with scope, audit type, lead auditor, and finding tracking.",
    category: "audit-checklists",
    categoryLabel: "Audit Checklists",
    fileType: "DOCX",
    pages: 7,
    downloads: 1490,
    updatedAt: "February 2026",
    sections: [
      "Quarterly audit calendar",
      "Scope definitions",
      "Finding severity matrix",
      "CAPA tracking sheet",
    ],
  },
  {
    slug: "sop-allergen-changeover",
    title: "SOP — Allergen Changeover on Shared Lines",
    description: "Validated changeover procedure including cleaning verification and first-product disposition rules.",
    category: "sop-templates",
    categoryLabel: "SOP Templates",
    fileType: "DOCX",
    pages: 9,
    downloads: 1080,
    updatedAt: "April 2026",
    sections: [
      "Pre-changeover documentation",
      "Cleaning steps & verification",
      "First-product test plan",
      "Release criteria",
    ],
  },
  {
    slug: "labelling-review-template",
    title: "Labeling Review Template (FSSAI 2026)",
    description: "Pre-print label review checklist aligned to current FSSAI labeling regulations and front-of-pack rules.",
    category: "compliance-docs",
    categoryLabel: "Compliance Docs",
    fileType: "PDF",
    pages: 5,
    downloads: 1670,
    updatedAt: "May 2026",
    sections: [
      "Mandatory declarations",
      "Nutrition panel formatting",
      "Allergen statements",
      "Claim substantiation",
    ],
  },
];

const SERVICES = [
  {
    slug: "fssai-compliance",
    name: "FSSAI Compliance",
    short: "License, renewals, and category-specific compliance support.",
    icon: "shield",
  },
  {
    slug: "haccp-development",
    name: "HACCP Development",
    short: "End-to-end HACCP plan development with audit-ready documentation.",
    icon: "clipboard",
  },
  {
    slug: "food-safety-docs",
    name: "Food Safety Documentation",
    short: "SOPs, work instructions, and record systems that auditors expect.",
    icon: "file",
  },
  {
    slug: "product-development",
    name: "Product Development Guidance",
    short: "Formulation, shelf-life, scale-up — with regulatory checkpoints baked in.",
    icon: "flask",
  },
  {
    slug: "qms-setup",
    name: "QMS Setup",
    short: "Quality Management System design aligned to GFSI-recognized schemes.",
    icon: "layers",
  },
  {
    slug: "audit-preparation",
    name: "Audit Preparation & Support",
    short: "Mock audits, gap analysis, and on-site support during certification.",
    icon: "check",
  },
];

const STATS = [
  { num: "120+", label: "Articles Published" },
  { num: "48",   label: "Templates" },
  { num: "12",   label: "Industry Topics" },
  { num: "85+",  label: "Consultations Done" },
];

/* ─────────────────────────── PHASE 2 DATA ─────────────────────────── */

const JOB_TYPES = ["Full-time", "Part-time", "Contract", "Remote", "Internship"];
const EXPERIENCE_LEVELS = ["Entry-level", "Mid-level", "Senior", "Lead"];

const JOBS = [
  {
    id: "j-1",
    title: "Quality Assurance Manager",
    company_name: "Amul Foods",
    company_initial: "AF",
    location: "Anand, Gujarat",
    job_type: "Full-time",
    remote: false,
    salary_min: 1200000,
    salary_max: 1800000,
    experience_level: "Senior",
    description: "Lead QA across two dairy lines (UHT milk and ice-cream). Own HACCP, GMP, and supplier qualification programs.",
    skills: ["HACCP", "FSSAI", "ISO 22000", "Dairy"],
    posted: "2 days ago",
    applications: 24,
    featured: true,
  },
  {
    id: "j-2",
    title: "Food Safety Auditor (Third-party)",
    company_name: "TÜV India",
    company_initial: "TI",
    location: "Mumbai · Remote OK",
    job_type: "Full-time",
    remote: true,
    salary_min: 900000,
    salary_max: 1400000,
    experience_level: "Mid-level",
    description: "Conduct on-site audits across FSSC 22000, BRC, and SQF schemes. Heavy travel (40-50%).",
    skills: ["Auditing", "FSSC 22000", "BRC"],
    posted: "5 days ago",
    applications: 18,
  },
  {
    id: "j-3",
    title: "R&D Food Technologist",
    company_name: "ITC Foods",
    company_initial: "IT",
    location: "Bengaluru, Karnataka",
    job_type: "Full-time",
    remote: false,
    salary_min: 700000,
    salary_max: 1100000,
    experience_level: "Mid-level",
    description: "New product development for the snacks and biscuits portfolio. Formulation, sensory, and pilot-scale trials.",
    skills: ["NPD", "Formulation", "Sensory", "Snacks"],
    posted: "1 week ago",
    applications: 47,
  },
  {
    id: "j-4",
    title: "Regulatory Affairs Specialist",
    company_name: "Hindustan Unilever",
    company_initial: "HU",
    location: "Gurugram, Haryana",
    job_type: "Full-time",
    remote: false,
    salary_min: 1000000,
    salary_max: 1500000,
    experience_level: "Senior",
    description: "Manage FSSAI submissions and labeling reviews for the nutraceuticals and packaged foods portfolio.",
    skills: ["FSSAI", "Labeling", "Nutraceuticals"],
    posted: "3 days ago",
    applications: 31,
  },
  {
    id: "j-5",
    title: "Production Supervisor — Bakery",
    company_name: "Britannia Industries",
    company_initial: "BI",
    location: "Hyderabad, Telangana",
    job_type: "Full-time",
    remote: false,
    salary_min: 500000,
    salary_max: 750000,
    experience_level: "Mid-level",
    description: "Shift supervision on a high-speed biscuit line. GMP, line efficiency, and SOP adherence.",
    skills: ["Production", "GMP", "Bakery"],
    posted: "6 days ago",
    applications: 22,
  },
  {
    id: "j-6",
    title: "QC Microbiologist",
    company_name: "Mother Dairy",
    company_initial: "MD",
    location: "Delhi NCR",
    job_type: "Full-time",
    remote: false,
    salary_min: 450000,
    salary_max: 650000,
    experience_level: "Entry-level",
    description: "Daily micro testing on incoming milk, in-process, and finished product. Method validation and report-out.",
    skills: ["Microbiology", "QC", "Method Validation"],
    posted: "4 days ago",
    applications: 38,
  },
  {
    id: "j-7",
    title: "Compliance Consultant (Contract)",
    company_name: "Independent",
    company_initial: "IC",
    location: "Pan-India · Remote",
    job_type: "Contract",
    remote: true,
    salary_min: 80000,
    salary_max: 150000,
    experience_level: "Senior",
    description: "3-6 month engagements supporting growing F&B brands through FSSAI Tier-2 license upgrades and audits.",
    skills: ["FSSAI", "Consulting", "Audit Prep"],
    posted: "1 day ago",
    applications: 9,
  },
  {
    id: "j-8",
    title: "Food Technology Intern",
    company_name: "Slurrp Farm",
    company_initial: "SF",
    location: "Bengaluru, Karnataka",
    job_type: "Internship",
    remote: false,
    salary_min: 25000,
    salary_max: 35000,
    experience_level: "Entry-level",
    description: "6-month internship in the R&D team. Recipe trials, shelf-life studies, and packaging compatibility tests.",
    skills: ["R&D", "Shelf Life", "Packaging"],
    posted: "1 week ago",
    applications: 64,
  },
];

const SPECIALIZATIONS = [
  "Food Safety", "Quality Control", "Regulatory Compliance",
  "HACCP", "Product Development", "Sensory Analysis",
  "Process Engineering", "Auditing", "Nutraceuticals",
  "Labeling", "Dairy", "Bakery", "Beverages", "Snacks",
];

const EXPERTS = [
  {
    id: "e-1",
    name: "Dr. Aarti Menon",
    avatar: "AM",
    title: "FSSAI Lead Auditor",
    location: "Mumbai · India",
    experience_years: 12,
    rate: "₹6,000/hr",
    rating: 4.9,
    reviews: 38,
    specializations: ["Food Safety", "HACCP", "Auditing"],
    certifications: ["FSSAI Auditor", "FSSC 22000 Lead Auditor", "PhD Food Tech"],
    bio: "Twelve years auditing and implementing food safety systems for Indian food businesses. Trainer at NIFTEM workshops.",
    available: true,
    featured: true,
  },
  {
    id: "e-2",
    name: "Vikram Shah",
    avatar: "VS",
    title: "Regulatory Affairs Consultant",
    location: "Delhi NCR · India",
    experience_years: 9,
    rate: "₹4,500/hr",
    rating: 4.8,
    reviews: 27,
    specializations: ["Regulatory Compliance", "Labeling", "Nutraceuticals"],
    certifications: ["MSc Food Tech", "FSSAI Trainer"],
    bio: "Specializes in FSSAI licensing, nutraceutical compliance, and labeling reviews across India.",
    available: true,
  },
  {
    id: "e-3",
    name: "Priya Iyer",
    avatar: "PI",
    title: "QC Manager · Dairy",
    location: "Anand, Gujarat",
    experience_years: 14,
    rate: "₹5,500/hr",
    rating: 4.9,
    reviews: 42,
    specializations: ["Quality Control", "Dairy", "Sensory Analysis"],
    certifications: ["BSc + MSc Food Tech", "Six Sigma Black Belt"],
    bio: "Quality Control lead with deep experience in dairy. Shelf-life testing, sampling plans, and incoming-material inspection.",
    available: false,
  },
  {
    id: "e-4",
    name: "Devansh Roy",
    avatar: "DR",
    title: "Process Engineer",
    location: "Pune, Maharashtra",
    experience_years: 8,
    rate: "₹4,800/hr",
    rating: 4.7,
    reviews: 19,
    specializations: ["Process Engineering", "Product Development", "Snacks"],
    certifications: ["BTech Food Engineering", "Extrusion Specialist"],
    bio: "Process engineer with 8 years on extrusion, thermal, and aseptic lines. Helps food businesses scale up without sacrificing margins.",
    available: true,
  },
  {
    id: "e-5",
    name: "Naina Kapoor",
    avatar: "NK",
    title: "Industry Analyst & Strategy",
    location: "Bengaluru · India",
    experience_years: 6,
    rate: "₹3,800/hr",
    rating: 4.6,
    reviews: 14,
    specializations: ["Strategy", "Market Research", "Nutraceuticals"],
    certifications: ["MBA · IIM", "Food Tech Researcher"],
    bio: "Covers Indian food-tech investment, market structure, and category trends. Previously at a leading consumer-sector research firm.",
    available: true,
  },
  {
    id: "e-6",
    name: "Rohan Pillai",
    avatar: "RP",
    title: "Sensory Scientist",
    location: "Chennai, Tamil Nadu",
    experience_years: 10,
    rate: "₹5,000/hr",
    rating: 4.8,
    reviews: 22,
    specializations: ["Sensory Analysis", "Product Development", "Beverages"],
    certifications: ["MSc Food Tech", "Certified Sensory Panel Leader"],
    bio: "Sensory scientist working with beverage and savory brands. Panel design, descriptive analysis, and consumer testing.",
    available: true,
  },
  {
    id: "e-7",
    name: "Meera Banerjee",
    avatar: "MB",
    title: "Nutrition & Labeling Consultant",
    location: "Kolkata · West Bengal",
    experience_years: 11,
    rate: "₹4,200/hr",
    rating: 4.9,
    reviews: 31,
    specializations: ["Labeling", "Nutraceuticals", "Regulatory Compliance"],
    certifications: ["MSc Nutrition", "FSSAI Trainer"],
    bio: "Nutrition and labeling expert. Pre-print label reviews, claim substantiation, and front-of-pack compliance.",
    available: true,
    featured: true,
  },
  {
    id: "e-8",
    name: "Karthik Subramanian",
    avatar: "KS",
    title: "Plant Operations Consultant",
    location: "Hyderabad · India",
    experience_years: 15,
    rate: "₹6,500/hr",
    rating: 4.8,
    reviews: 36,
    specializations: ["Process Engineering", "Bakery", "Auditing"],
    certifications: ["BTech + MTech", "GFSI Trained"],
    bio: "Plant operations and turnaround specialist. Helps mid-sized food manufacturers improve OEE and pass audits the first time.",
    available: false,
  },
];

const AUTHORS = {
  "Aarti Menon": {
    name: "Aarti Menon",
    role: "FSSAI Auditor · 12 yrs",
    bio: "Founder of foodnme. Twelve years auditing and implementing food safety systems for Indian food businesses. Trainer at NIFTEM workshops.",
    linkedin: "https://www.linkedin.com/",
    twitter: "https://twitter.com/",
    articleCount: 24,
  },
  "Vikram Shah": {
    name: "Vikram Shah",
    role: "Regulatory Consultant",
    bio: "Specializes in FSSAI licensing, nutraceutical compliance, and labeling reviews. Former regulatory affairs lead at a national QSR chain.",
    linkedin: "https://www.linkedin.com/",
    twitter: "https://twitter.com/",
    articleCount: 18,
  },
  "Priya Iyer": {
    name: "Priya Iyer",
    role: "QC Manager · Dairy",
    bio: "Quality Control lead at a mid-sized dairy processor. Writes on shelf-life testing, sampling plans, and incoming-material inspection.",
    linkedin: "https://www.linkedin.com/",
    twitter: "https://twitter.com/",
    articleCount: 14,
  },
  "Devansh Roy": {
    name: "Devansh Roy",
    role: "Process Engineer",
    bio: "Process engineer with 8 years on extrusion, thermal, and aseptic lines. Helps food businesses scale up without sacrificing safety margins.",
    linkedin: "https://www.linkedin.com/",
    twitter: "https://twitter.com/",
    articleCount: 11,
  },
  "Naina Kapoor": {
    name: "Naina Kapoor",
    role: "Industry Analyst",
    bio: "Covers Indian food-tech investment, market structure, and category trends. Previously at a leading consumer-sector research firm.",
    linkedin: "https://www.linkedin.com/",
    twitter: "https://twitter.com/",
    articleCount: 9,
  },
};

window.FN_DATA = { CATEGORIES, TEMPLATE_CATEGORIES, ARTICLES, TEMPLATES, SERVICES, STATS, AUTHORS, JOBS, EXPERTS, SPECIALIZATIONS, JOB_TYPES, EXPERIENCE_LEVELS };
